version: '3.2'

services:

  boagent:
    build:
      context: .
    environment:
      BOAVIZTAPI_ENDPOINT: "http://boaviztapi:5000"
      DEFAULT_LIFETIME: 5.0
      HARDWARE_FILE_PATH: "/home/boagent/hardware_data.json"
      POWER_FILE_PATH: "/app/data/power_data.json"
    privileged: true
    depends_on:
      - boaviztapi
      - scaphandre
    ports:
      - "8000:8000"
    networks:
      - boagent-network
    volumes:
      - "/proc:/proc"
      - "/sys:/sys:ro"
      - "powerdata:/app/data:ro"
      - "./db:/app/db"
      - "../boaviztapi/boaviztapi:/app/boaviztapi"
      - "/etc/crontab:/etc/crontab"
      - "./boagent:/home/boagent/boagent"

  scaphandre:
    image: hubblo/scaphandre:dev
    privileged: true
    volumes:
      - type: bind
        source: /proc
        target: /proc
      - type: bind
        source: /sys/class/powercap
        target: /sys/class/powercap
      - "powerdata:/app/data:rw"
    command: [ "--no-header", "json", "-s", "10", "--resources", "-f", "/app/data/power_data.json" ]
    networks:
      - boagent-network

  boaviztapi:
    image: ghcr.io/boavizta/boaviztapi:1.2.2
    ports:
      - "5000:5000"
    networks:
      - boagent-network

volumes:
  powerdata: {}

networks:
  boagent-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.33.0/24
