[tool.poetry]
name = "boagent"
version = "0.9.0"
description = "Local API to collect and compute data on used device and running applications to give insight on their environmental impacts."
authors = []
license = "Apache-2.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
boaviztapi-sdk = "^1.2.4"
croniter = "^1.3.7"
fastapi = "^0.110.0"
pandas = "^2.2.1"
pydantic = "^2.6.4"
pydantic-settings = "^2.2.1"
requests = "^2.28.1"
SQLAlchemy = "^1.4.42"
uvicorn = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
