name: build_packages

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
      - 'test/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'Dockerfile'
      - 'CITATION'
      - 'book.toml'
      - 'CONTRIBUTING.md'

env:
  CARGO_TERM_COLOR: always

    #jobs:
    #  build:
    #    name: build_python_package
    #    runs-on: ubuntu-latest
    #    steps:
    #      - name: Checkout repository
    #        uses: actions/checkout@v2
    #      - name: Install python dependencies
    #        uses: actions/setup-python@v2
    #        with:
    #          python-version: '3.x'
    #      - name: Install requirements
    #        run: |
    #          sudo apt update -y
    #          sudo apt install docker.io containerd runc wget python3-pip -y
    #          pip3 install pipenv twine
    #      - name: Run the API locally
    #        run: |
    #          python3 setup.py sdist
    #          API_VERSION=$(cat boagent/__init__.py | cut -d "'" -f 2)
    #          echo "API_VERSION=${API_VERSION}" >> $GITHUB_ENV
    #          docker build --build-arg VERSION=${API_VERSION} . --file Dockerfile --tag boagent:latest
    #          docker run -p "5000:5000" --name=boagent -tid boagent:latest
    #      - name: Get logs from the API container in case of a failure
    #        run: |
    #          docker logs boagent
    #      - name: Build the pip package and push it
    #        run: |
    #          sudo chown -R $(whoami) boagent
    #          SDK_VERSION=${{ env.API_VERSION }}
    #          echo "SDK_VERSION == ${SDK_VERSION}"
    #          cd boagent
    #          sed -i "s/^VERSION.*/VERSION = \"${SDK_VERSION}\"/" setup.py
    #          sed -i "s/^    long_description=.*/long_description='Python SDK for boagent'/" setup.py
    #          sed -i 's/    #.*//' setup.py
    #          sed -i 's/    """.*//' setup.py
    #          python3 setup.py sdist
    #          pipenv run twine upload --repository pypi --username __token__ --password ${{ secrets.BPETIT_SECRET_PYPI_TOKEN }} dist/*
