name: Publish release

on:
  push:
    branches:
      - 'greenhack22'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build  docker image
        run: docker build . --tag ghcr.io/boavizta/boagent:greenhack22

      - name: Push docker image
        run: docker push ghcr.io/boavizta/boagent:greenhack22
