name: Publish release

on:
  release:
    types: [published]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install poetry
        run: python -m pip install --upgrade poetry wheel

      - name: Build  docker image
        run: docker build . --tag ghcr.io/boavizta/boagent:$(poetry version -s)

      - name: Push docker image
        run: docker push ghcr.io/boavizta/boagent:$(poetry version -s)
