name: Execute tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "boagent/**"
      - "tests/**"
      - "poetry.lock"
      - "pyproject.toml"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "boagent/**"
      - "tests/**"
      - "poetry.lock"
      - "pyproject.toml"

jobs:
  test:
    strategy:
      matrix:
        version: ["3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: Poetry setup
        run : python3 -m pip install --upgrade poetry wheel
      - name: Install dependencies
        run: poetry install
      - name: Execute tests
        run: poetry run python3 -m pytest
